#---------------------------------#
#         version format          #
#---------------------------------#
version: 1.2.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#
os: Visual Studio 2015


#---------------------------------#
#            patching             #
#---------------------------------#
assembly_info:
  patch: true
  file: src\SolutionInfo.cs
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'


#---------------------------------#
#              build              #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

skip_tags: true

build:
  verbosity: minimal


#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - cmd: set SOLUTION=src\MvvmDialogs.sln
  - cmd: set NUSPEC=src\MvvmDialogs.nuspec
  - cmd: set NETPROJECT=src\NET\MvvmDialogs\MvvmDialogs.csproj
  - cmd: set UNIVERSALPROJECT=src\Universal\MvvmDialogs\MvvmDialogs.csproj
  - cmd: set LOGGER=C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll

  - cmd: nuget restore %SOLUTION%
  
  # Build solution in default configuration
  - cmd: msbuild %SOLUTION% /t:Rebuild /p:Configuration=Release /m /logger:"%LOGGER%"

  # Build .NET project in additional versions
  - cmd: msbuild %NETPROJECT% /t:Rebuild /p:Configuration=Release;TargetFrameworkVersion=v4.0 /m /logger:"%LOGGER%"
  - cmd: msbuild %NETPROJECT% /t:Rebuild /p:Configuration=Release;TargetFrameworkVersion=v3.5 /m /logger:"%LOGGER%"

  - cmd: nuget pack %NUSPEC% -version %APPVEYOR_BUILD_VERSION%-beta


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies: '**\bin\Release\*Test.dll'


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
- path: '*.nupkg'
  name: NuGet


#---------------------------------#
#              nuget              #
#---------------------------------#
nuget:
  project_feed: true


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
  - provider: Email
    to:
      - mattias.kindborg@email.com
    on_build_status_changed: true
